[tool.poetry]
name = "dnd driver"
version = "0.1.0"
description = ""
authors = ["Thomas Vos <vossy01@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
selenium = "^4.13.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
