"""empty message

Revision ID: 11134298249f
Revises: e367dc292558
Create Date: 2023-10-04 22:42:01.626181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11134298249f'
down_revision = 'e367dc292558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_filename'), ['filename'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_filename'))

    # ### end Alembic commands ###
