"""empty message

Revision ID: 30eaa9009ac2
Revises: ccbe29c0f68e
Create Date: 2023-10-29 10:20:28.937905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30eaa9009ac2'
down_revision = 'ccbe29c0f68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_participants_image_id_images'), 'images', ['image_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_participants_image_id_images'), type_='foreignkey')
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###
