"""empty message

Revision ID: 426260793b9b
Revises: 1cdd9492083a
Create Date: 2023-10-05 13:51:27.422258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426260793b9b'
down_revision = '1cdd9492083a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('focus_x', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('focus_y', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dimension_x', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('dimension_y', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('dimension_y')
        batch_op.drop_column('dimension_x')
        batch_op.drop_column('focus_y')
        batch_op.drop_column('focus_x')

    # ### end Alembic commands ###
