"""empty message

Revision ID: 609434c2d7b7
Revises: f5de8e81046b
Create Date: 2023-10-05 14:36:06.016442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609434c2d7b7'
down_revision = 'f5de8e81046b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('hash',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_images_hash'), ['hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_hash'))
        batch_op.alter_column('hash',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
