"""combat

Revision ID: 7422632de568
Revises: e8adab12c337
Create Date: 2023-10-28 14:39:18.735948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7422632de568'
down_revision = 'e8adab12c337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_combat'))
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hit_dice', sa.String(length=50), nullable=False),
    sa.Column('ac', sa.Integer(), nullable=False),
    sa.Column('cr', sa.String(length=10), nullable=False),
    sa.Column('initiative_modifier', sa.Integer(), nullable=False),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('is_PC', sa.Boolean(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_entities_image_id_images')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities'))
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('combat_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('ac', sa.Integer(), nullable=False),
    sa.Column('initiative', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.String(length=256), nullable=False),
    sa.Column('has_reaction', sa.Boolean(), nullable=False),
    sa.Column('colour', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['combat_id'], ['combat.id'], name=op.f('fk_participants_combat_id_combat')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_participants_entity_id_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participants'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participants')
    op.drop_table('entities')
    op.drop_table('combat')
    # ### end Alembic commands ###
