"""empty message

Revision ID: ccbe29c0f68e
Revises: 1da212a10f5d
Create Date: 2023-10-29 00:48:46.205394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ccbe29c0f68e"
down_revision = "1da212a10f5d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_PC", sa.Boolean(), nullable=False, server_default=0)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.drop_column("is_PC")

    # ### end Alembic commands ###
