"""empty message

Revision ID: e367dc292558
Revises: c7ae33e29399
Create Date: 2023-10-04 22:09:56.321517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e367dc292558'
down_revision = 'c7ae33e29399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_tags',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_image_tags_image_id_images')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_image_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('image_id', 'tag_id', name=op.f('pk_image_tags'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_tags')
    # ### end Alembic commands ###
